### PR TITLE
Gain some milliseconds

### PR DESCRIPTION
**Pull request by jean-m-cyr**
Optimize loop

### CODE REVIEW

**Comment by ZiCog** [comment]
Neat. A 17% speed boost!

**Comment by jean-m-cyr** [comment]
Hey Heater,
It was fun debating at the Pi forums, but it became a bit of an obsession. Not to mention that I found the moderators insufferable. Requested that they delete my userid.
Anyway, thanks for the stimulating chatter over the past few.

**Comment by ZiCog** [comment]
Hi there.

Yes it was fun.

Yes it can get obsessive!

Yes, the moderators can be a pain. Amazingly they can be even worse. As I found over here: https://users.rust-lang.org/

You will be missed. Take care. All the best.

**Comment by ZiCog** [comment]
Hei jean-m-cyr,

Back on the forum ejolson is asking: "Is there anyway to get a copy of the CUDA code for solving Tatami challenge? I was still trying to understand it and would like very much to see it again."

I though perhaps you might like to add it here as a pull request.

**Comment by jean-m-cyr** [comment]
He's got it already... via email

**Comment by ZiCog** [comment]
OK thanks. 

All the best.

**Comment by jean-m-cyr** [comment]
``` 
jcyr@jetson-nano:~/tatami$ cat tatami.cu

// tatami.cu

#include <cuda.h>
#include <iostream>

const unsigned nMax(100000000);
const unsigned nMaxSqrt(sqrt(nMax));

__global__ void odd(unsigned* v, unsigned base)
{
    unsigned i = (blockIdx.x * blockDim.x + threadIdx.x + base) * 2 + 7;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        __syncthreads();
        for (unsigned j = k2 / 2; j <= k4 / 2; j++)
            atomicAdd(&v[i * j], 1);
        __syncthreads();
        k2 += i + 1;
        k3 += i - 1;
    }
    __syncthreads();
}

__global__ void even(unsigned* v, unsigned base)
{
    unsigned i = (blockIdx.x * blockDim.x + threadIdx.x + base) * 2 + 8;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        __syncthreads();
        for (unsigned j = k2; j <= k4; ++j)
            atomicAdd(&v[i * j / 2], 1);
        __syncthreads();
        k2 += i + 1;
        k3 += i - 1;
    }
    __syncthreads();
}

int Tatami(int s)
{
    unsigned* v;

    cudaMalloc(&v, sizeof(unsigned) * nMax);
    cudaMemset(v, 0, sizeof(unsigned) * nMax);
    const unsigned group_size = 1024;
    {
        // for (int i = 8; i < nMaxSqrt; i += 2)
        const unsigned iterations = (nMaxSqrt - 8) / 2;
        const unsigned groups = iterations / group_size;
        const unsigned trailing_group_size = iterations - group_size * groups;
        even<<<groups, group_size>>>(v, 0);
        if (trailing_group_size)
            even<<<1, trailing_group_size>>>(v, groups * group_size);
    }
    {
        // for (int i = 7; i < nMaxSqrt; i += 2)
        const unsigned iterations = (nMaxSqrt - 7) / 2;
        const unsigned groups = iterations / group_size;
        const unsigned trailing_group_size = iterations - group_size * groups;
        odd<<<groups, group_size>>>(v, 0);
        if (trailing_group_size)
            odd<<<1, trailing_group_size>>>(v, groups * group_size);
    }
    cudaDeviceSynchronize(); // Ought not be required since cudaMemcpy is synchronous!!!

    unsigned* vh = (unsigned*)malloc(sizeof(unsigned) * nMax);
    cudaMemcpy(vh, v, sizeof(unsigned) * nMax, cudaMemcpyDeviceToHost);

    cudaDeviceSynchronize(); // Ought not be required since cudaMemcpy is synchronous!!!
   
    for (unsigned i = 0; i < nMax; ++i)
        if (vh[i] == s)
            return i + i;
    return 0;  // shouldn't happen
}

int main()
{
    int s = 200;
    std::cout << "T(" << Tatami(s) << ")=" << s << std::endl;
}

jcyr@jetson-nano:~/tatami$ /usr/local/cuda/bin/nvcc -O3 tatami.cu 
jcyr@jetson-nano:~/tatami$ ./a.out 
T(85765680)=200
jcyr@jetson-nano:~/tatami$
```

**Comment by jean-m-cyr** [comment]
On NVidia GTX 1060

```
jcyr@miner:~/tatami$ /usr/local/cuda/bin/nvcc -O3 tatami.cu 
jcyr@miner:~/tatami$ time ./a.out
T(85765680)=200

real    0m0.570s
user    0m0.404s
sys     0m0.156s
jcyr@miner:~/tatami$
```

jetson nano has pretty poor CUDA performance since it implements CUDA local memory as PCIe accessed host memory.

**Comment by ZiCog** [comment]
Hi jean-m-cyr,

Thank you for that. Unfortunately it does not work on my Jetson Nano:
```
heater@jetson2:~/tatami-rust$ nvcc --version 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Mon_Mar_11_22:13:24_CDT_2019
Cuda compilation tools, release 10.0, V10.0.326
heaterl@jetson2:~/tatami-rust$ /usr/local/cuda/bin/nvcc -O3 tatami3.cu 
heater@jetson2:~/tatami-rust$ ./a.out
T(0)=200
```
Do I have a wrong nvcc version or something?

**Comment by jean-m-cyr** [comment]
That is odd, same jetson nano, different results. I admit that I don't understand why. Same compiler version. I think it may have something to do with the atomicAdd. It may not be so atomic over the PCIe interface to host RAM.

**Comment by ZiCog** [comment]
Odd indeed. I don't think this is Jetson Nano specific. ejolson was not getting it to work either. What he said on the Raspi forum was:

> _I tried it using CUDA version 8.0 on an older GT630 and it immediately returns with T(0)=200 which is wrong; I tried it with CUDA version 10.2 on a TITAN-V and it hung at full CPU for 2 minutes before I killed it. I have not tried on a Jetson and would be interested if it works._

**Comment by jean-m-cyr** [comment]
The GT360 uses host RAM just like the Jetson. The Titan-V has 24GB of on board DDR so there goes my theory regarding PCIe access to host memory. Oh well, mystery remains unsolved.

**Comment by ZiCog** [comment]
Dang!

Any experiments we could do to help resolve the mystery?

**Comment by jean-m-cyr** [comment]
I'd be curious to see the following value. It should be 200

```
    std::cout << vh[85765680 / 2] << std::endl; // Dump the solution slot.
    for (unsigned i = 0; i < nMax; ++i)
        if (vh[i] == s)
            return i + i;
```

**Comment by jean-m-cyr** [comment]
Ah, something weird definitely going on. 
```
jcyr@jetson-nano:~/tatami$ /usr/local/cuda/bin/nvcc -O3 tatami.cu
jcyr@jetson-nano:~/tatami$ ./a.out 
T(85765680)=200
jcyr@jetson-nano:~/tatami$ /usr/local/cuda/bin/nvcc -O3  -gencode arch=compute_53,code=[sm_53,compute_53] tatami.cu
jcyr@jetson-nano:~/tatami$ ./a.out 
T(0)=200
jcyr@jetson-nano:~/tatami$
```
Doesn't happen all of the time, but finally reproduced the problem.

**Comment by jean-m-cyr** [comment]
Not sure why this would work any better with these few changes

```
jcyr@jetson-nano:~/tatami$ cat tatami.cu 
// tatami.cu

#include <cuda.h>
#include <iostream>

const unsigned nMax(100000000);
const unsigned nMaxSqrt(sqrt(nMax));

__global__ void odd(unsigned* v, unsigned base)
{
    unsigned i = (blockIdx.x * blockDim.x + threadIdx.x + base) * 2 + 7;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        __syncthreads();
        for (unsigned j = k2 / 2; j <= k4 / 2; j++)
            atomicInc(&v[i * j], 0xffffffff);
        __syncthreads();
        k2 += i + 1;
        k3 += i - 1;
    }
}

__global__ void even(unsigned* v, unsigned base)
{
    unsigned i = (blockIdx.x * blockDim.x + threadIdx.x + base) * 2 + 8;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        __syncthreads();
        for (unsigned j = k2; j <= k4; ++j)
            atomicInc(&v[i * j / 2], 0xffffffff);
        __syncthreads();
        k2 += i + 1;
        k3 += i - 1;
    }
}

int Tatami(int s)
{
    unsigned* v;

    cudaMalloc(&v, sizeof(unsigned) * nMax);
    cudaMemset(v, 0, sizeof(unsigned) * nMax);
    const unsigned group_size = 1024;

    unsigned iterations = (nMaxSqrt - 8) / 2;
    unsigned groups = iterations / group_size;
    unsigned trailing_group_size = iterations - group_size * groups;
    even<<<groups, group_size>>>(v, 0);
    if (trailing_group_size)
        even<<<1, trailing_group_size>>>(v, groups * group_size);

    iterations = (nMaxSqrt - 7) / 2;
    groups = iterations / group_size;
    trailing_group_size = iterations - group_size * groups;
    odd<<<groups, group_size>>>(v, 0);
    if (trailing_group_size)
        odd<<<1, trailing_group_size>>>(v, groups * group_size);

    unsigned* vh = (unsigned*)malloc(sizeof(unsigned) * nMax);
    cudaMemcpy(vh, v, sizeof(unsigned) * nMax, cudaMemcpyDeviceToHost);

    for (unsigned i = 0; i < nMax; ++i)
        if (vh[i] == s)
            return i + i;
    return 0;  // shouldn't happen
}

int main()
{
    int s = 200;
    std::cout << "T(" << Tatami(s) << ")=" << s << std::endl;
}

jcyr@jetson-nano:~/tatami$ /usr/local/cuda/bin/nvcc -O3 tatami.cu
jcyr@jetson-nano:~/tatami$ time ./a.out 
T(85765680)=200

real    0m7.386s
user    0m0.312s
sys     0m0.596s
jcyr@jetson-nano:~/tatami$ 
```

**Comment by ZiCog** [comment]
So I took that last listing and added the "Dump the solution slot." modification. Still no go. Now it does this:
```
zicog@jetson2:~/tatami-rust$ /usr/local/cuda/bin/nvcc -O3 tatami4.cu -o tatami4
tatami4     tatami4.cu  
zicog@jetson2:~/tatami-rust$ /usr/local/cuda/bin/nvcc -O3 tatami4.cu -o tatami4
zicog@jetson2:~/tatami-rust$ time ./tatami4 
T(0
0)=200

real	0m4,783s
user	0m0,292s
sys	0m0,352s
```
I tried running it a bunch of times.

**Comment by jean-m-cyr** [comment]
Yes, I am seeing the same thing, all 0's in the count array, in the few instances I've been able to reproduce the odd result. It's like the device array is not being copied back to the host array!
One observation... Your jetson is running twice as fast as mine!

**Comment by ZiCog** [comment]
Cool. I have not done any tweaking to this Jetson installation.

**Comment by jean-m-cyr** [comment]
This is truly odd. The following C++ code simulates the CUDA version and works perfectly!

Your CUDA version running twice as fast leads be to believe that one of the CUDA kernels may be crashing. Probably ought to add some error checking code.

```
jcyr@jetson-nano:~/tatami$ cat tatami.cpp 
// tatami.cu

#include <iostream>
#include <cmath>
#include <assert.h>

const unsigned nMax(100000000);
const unsigned nMaxSqrt(sqrt(nMax));

void odd(unsigned* v, unsigned base, unsigned blockIdxx, unsigned blockDimx, unsigned threadIdxx)
{
    unsigned i = (blockIdxx * blockDimx + threadIdxx + base) * 2 + 7;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        for (unsigned j = k2 / 2; j <= k4 / 2; j++)
        {
            assert(i * j < nMax);
            v[i * j]++;
        }
        k2 += i + 1;
        k3 += i - 1;
    }
}

void even(unsigned* v, unsigned base, unsigned blockIdxx, unsigned blockDimx, unsigned threadIdxx)
{
    unsigned i = (blockIdxx * blockDimx + threadIdxx + base) * 2 + 8;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        for (unsigned j = k2; j <= k4; ++j)
        {
            assert(i * j / 2 < nMax);
            v[i * j / 2]++;
        }
        k2 += i + 1;
        k3 += i - 1;
    }
}

int Tatami(int s)
{
    unsigned* v = (unsigned*)malloc(sizeof(unsigned) * nMax);

    const unsigned group_size = 1024;

    unsigned iterations = (nMaxSqrt - 8) / 2;
    unsigned groups = iterations / group_size;
    unsigned trailing_group_size = iterations - group_size * groups;
    for (int group = 0; group < groups; group++)
        for (int thread = 0; thread < group_size; thread++)
            even(v, 0, group, group_size, thread);
    if (trailing_group_size)
        for (int thread = 0; thread < trailing_group_size; thread++)
            even(v, groups * group_size, 0, group_size, thread);

    iterations = (nMaxSqrt - 7) / 2;
    groups = iterations / group_size;
    trailing_group_size = iterations - group_size * groups;
    for (int group = 0; group < groups; group++)
        for (int thread = 0; thread < group_size; thread++)
            odd(v, 0, group, group_size, thread);
    if (trailing_group_size)
        for (int thread = 0; thread < trailing_group_size; thread++)
            odd(v, groups * group_size, 0, group_size, thread);

    for (unsigned i = 0; i < nMax; ++i)
        if (v[i] == s)
            return i + i;
    return 0;  // shouldn't happen
}

int main()
{
    int s = 200;
    std::cout << "T(" << Tatami(s) << ")=" << s << std::endl;
}

jcyr@jetson-nano:~/tatami$ g++ tatami.cpp
jcyr@jetson-nano:~/tatami$ ./a.out 
T(85765680)=200
jcyr@jetson-nano:~/tatami$
```

**Comment by jean-m-cyr** [comment]
CUDA with error checking

```
// tatami.cu

#include <cuda.h>
#include <iostream>

#define gpuErrchk(ans) { gpuAssert((ans), __FILE__, __LINE__); }

inline void gpuAssert(cudaError_t code, const char *file, int line)
{
   if (code != cudaSuccess) 
   {
       fprintf(stderr,"GPUassert: %s %s %d\n", cudaGetErrorString(code), file, line);
       exit(code);
   }
}

const unsigned nMax(100000000);
const unsigned nMaxSqrt(sqrt(nMax));

__global__ void odd(unsigned* v, unsigned base)
{
    unsigned i = (blockIdx.x * blockDim.x + threadIdx.x + base) * 2 + 7;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        __syncthreads();
        for (unsigned j = k2 / 2; j <= k4 / 2; j++)
            atomicInc(&v[i * j], 0xffffffff);
        __syncthreads();
        k2 += i + 1;
        k3 += i - 1;
    }
}

__global__ void even(unsigned* v, unsigned base)
{
    unsigned i = (blockIdx.x * blockDim.x + threadIdx.x + base) * 2 + 8;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        __syncthreads();
        for (unsigned j = k2; j <= k4; ++j)
            atomicInc(&v[i * j / 2], 0xffffffff);
        __syncthreads();
        k2 += i + 1;
        k3 += i - 1;
    }
}

int Tatami(int s)
{
    unsigned* v;

    gpuErrchk(cudaMalloc(&v, sizeof(unsigned) * nMax));
    gpuErrchk(cudaMemset(v, 0, sizeof(unsigned) * nMax));
    const unsigned group_size = 1024;

    unsigned iterations = (nMaxSqrt - 8) / 2;
    unsigned groups = iterations / group_size;
    unsigned trailing_group_size = iterations - group_size * groups;
    even<<<groups, group_size>>>(v, 0);
    gpuErrchk(cudaPeekAtLastError());
    gpuErrchk(cudaDeviceSynchronize());
    if (trailing_group_size)
    {
        even<<<1, trailing_group_size>>>(v, groups * group_size);
        gpuErrchk(cudaPeekAtLastError());
        gpuErrchk(cudaDeviceSynchronize());
    }

    iterations = (nMaxSqrt - 7) / 2;
    groups = iterations / group_size;
    trailing_group_size = iterations - group_size * groups;
    odd<<<groups, group_size>>>(v, 0);
    gpuErrchk(cudaPeekAtLastError());
    gpuErrchk(cudaDeviceSynchronize());
    if (trailing_group_size)
    {
        odd<<<1, trailing_group_size>>>(v, groups * group_size);
        gpuErrchk(cudaPeekAtLastError());
        gpuErrchk(cudaDeviceSynchronize());
    }

    unsigned* vh = (unsigned*)malloc(sizeof(unsigned) * nMax);
    if (!vh)
    {
        fprintf(stderr, "malloc fails\n");
        exit(-1);
    }
    gpuErrchk(cudaMemcpy(vh, v, sizeof(unsigned) * nMax, cudaMemcpyDeviceToHost));

    for (unsigned i = 0; i < nMax; ++i)
        if (vh[i] == s)
            return i + i;
    return 0;  // shouldn't happen
}

int main()
{
    int s = 200;
    std::cout << "T(" << Tatami(s) << ")=" << s << std::endl;
}
```

**Comment by ZiCog** [comment]
BINGO!

With those error checks I got the following error:
```
$ nvcc -O3 tatami5.cu -o tatami5
zicog@jetson2:~/tatami-rust$ time ./tatami5
GPUassert: the launch timed out and was terminated tatami5.cu 71
T(
real	0m5,334s
user	0m0,020s
sys	0m0,416s
```
A quick google for "launch timed out and was terminated CUDA" soon found a lot of discussion about that. Something about CUDA operations being subject to a time out so that a hung GPU does not hang ones GUI.

OK, I disable X Windows and reboot into a text console with the following:
```
    $ sudo systemctl enable multi-user.target
    $ sudo systemctl set-default multi-user.target
```
Now we can run tatami with no crappy GUI/GPU intervention:
```
zicog@jetson2:~/tatami-rust$ time ./tatami5
T(85765680)=200

real	0m7,453s
user	0m0,264s
sys	0m0,404s
```
Perfect!

Now I wonder if there is a way to lengthen that CUDA timeout?

Thanks for taking all the trouble with this.

**Comment by jean-m-cyr** [comment]
Well, I learned something in the process.

PS. I run headless without X/GUI. Explains why I wasn't seeing it.

**Comment by ZiCog** [comment]
Yeah, who would have guessed!

I learned something as well. Always thought I should have a headless Jetson.

Thanks.

**Comment by jean-m-cyr** [comment]
Here's a version that runs with smaller CUDA kernels. Should prevent the problem.
```
// tatami.cu

#include <cuda.h>
#include <iostream>

const unsigned nMax(100000000);
const unsigned nMaxSqrt(sqrt(nMax));

__global__ void odd(unsigned* v, unsigned base)
{
    unsigned i = (threadIdx.x + base) * 2 + 7;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        __syncthreads();
        for (unsigned j = k2 / 2; j <= k4 / 2; j++)
            atomicInc(&v[i * j], 0xffffffff);
        __syncthreads();
        k2 += i + 1;
        k3 += i - 1;
    }
}

__global__ void even(unsigned* v, unsigned base)
{
    unsigned i = (threadIdx.x + base) * 2 + 8;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((k2 <= k3) && ((i * k2) < nMax))
    {
        unsigned k4 = (nMax - 1) / i;
        if (k3 < k4)
            k4 = k3;
        __syncthreads();
        for (unsigned j = k2; j <= k4; ++j)
            atomicInc(&v[i * j / 2], 0xffffffff);
        __syncthreads();
        k2 += i + 1;
        k3 += i - 1;
    }
}

int Tatami(int s)
{
    unsigned* v;

    cudaMalloc(&v, sizeof(unsigned) * nMax);
    cudaMemset(v, 0, sizeof(unsigned) * nMax);
    const unsigned max_group_size = 1024;

    unsigned iterations = (nMaxSqrt - 8) / 2;
    for (unsigned iteration = 0; iteration < iterations; iteration += max_group_size)
    {
        unsigned group_size = iterations - iteration;
        if (group_size > max_group_size)
            group_size = max_group_size;
        even<<<1, group_size>>>(v, iteration);
    }

    iterations = (nMaxSqrt - 7) / 2;
    for (unsigned iteration = 0; iteration < iterations; iteration += max_group_size)
    {
        unsigned group_size = iterations - iteration;
        if (group_size > max_group_size)
            group_size = max_group_size;
        odd<<<1, group_size>>>(v, iteration);
    }

    unsigned* vh = (unsigned*)malloc(sizeof(unsigned) * nMax);
    cudaMemcpy(vh, v, sizeof(unsigned) * nMax, cudaMemcpyDeviceToHost);

    for (unsigned i = 0; i < nMax; ++i)
        if (vh[i] == s)
            return i + i;

    return 0;  // shouldn't happen
}

int main()
{
    const unsigned s = 200;
    std::cout << "T(" << Tatami(s) << ")=" << s << std::endl;
}
```
Actually runs a little faster!

**Comment by jean-m-cyr** [comment]
How about a cargo with all the CUDA function bindings? Not sure how you would do the CUDA kernel launch syntax though.

**Comment by ZiCog** [comment]
More Bingo!

Your smaller CUDA kernel version works fine with the Ubuntu desktop:
```
zicogl@jetson2:~/tatami-rust$ time ./tatami6 
T(85765680)=200

real	0m7,512s
user	0m0,248s
sys	0m0,668s
```
A quick search for "Rust CUDA" turns up a bunch of efforts on making CUDA crates for Rust. I have no idea what state any of them are in.

**Comment by jean-m-cyr** [comment]
It's good to see interest in CUDA based parallelism. Do you a specific application in mind, or are you just playing with your new toy? :-)

**Comment by ZiCog** [comment]
Ah, well, this is all a total accident.

I have a bunch of Jetsons on my bench on account of a project our little company is involved in. So I had to demonstrate it could do what is required in terms of "AI" and real-time object detection from video and so on.

I know nothing of such things so that leads to a long investigation into "deep learning", Tensorflow, PyTorch and all kind of exotica.

Along the way I recall Tatami and your CUDA solution. Gotta try it right?

My curiosity drives me to at least try some experiments with CUDA. I doubt I have the chops to ever do anything useful with it.

**Comment by jean-m-cyr** [comment]
One last simplified version
```
// tatami.cu (simplified single kernel)

#include <cuda.h>
#include <iostream>

const unsigned nMax(100000000);
const unsigned nMaxSqrt(sqrt(nMax));

__global__ void count(unsigned* v, unsigned base)
{
    const unsigned i = threadIdx.x + base + 7;
    const unsigned loop_increment = (i & 1) + 1;
    unsigned k2 = i + 3;
    unsigned k3 = i + i - 4;
    while ((i * k2 < nMax) && (k2 <= k3))
    {
        const unsigned k4 = min((nMax - 1) / i, k3);
        for (unsigned j = k2; j <= k4; j += loop_increment)
            atomicAdd(v + i * j, 1);
        k2 += i + 1;
        k3 += i - 1;
    }
}

unsigned Tatami(unsigned s)
{
    unsigned* v;

    cudaMalloc(&v, sizeof(unsigned) * nMax);
    cudaMemset(v, 0, sizeof(unsigned) * nMax);
    const unsigned max_group_size = 1024;

    unsigned iterations = nMaxSqrt - 7;
    for (unsigned iteration = 0; iteration < iterations;
         iteration += max_group_size)
        count<<<1, min(iterations - iteration, max_group_size)>>>(v, iteration);

    unsigned* vh = new unsigned[nMax];
    cudaMemcpy(vh, v, sizeof(unsigned) * nMax, cudaMemcpyDeviceToHost);

    for (unsigned i = 7; i < nMax; i++)
        if (vh[i] == s)
            return i;

    return 0;  // shouldn't happen
}

int main()
{
    const unsigned s = 200;
    std::cout << "T(" << Tatami(s) << ")=" << s << std::endl;
}

jcyr@jetson-nano:~/tatami$ nvcc -O3 -arch compute_53 -code sm_53 tatami3.cu 
jcyr@jetson-nano:~/tatami$ time ./a.out 
T(85765680)=200

real    0m7.196s
user    0m0.408s
sys     0m0.720s
```

**Comment by ZiCog** [comment]
That works nicely as well.

Only one minor niggle. When I run it it hangs up my video object detection for seven seconds.

**Pull request merged**
